name: flutter_secure_storage
description: Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
version: 4.0.0
homepage: https://github.com/mogol/flutter_secure_storage

environment:
  sdk: '>=2.12.0-21.0.dev <3.0.0'
  flutter: '>=1.24.0-8.0.pre.102 <2.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.it_nomads.fluttersecurestorage
        pluginClass: FlutterSecureStoragePlugin
      ios:
        pluginClass: FlutterSecureStoragePlugin

dependencies:
  meta: '1.3.0-nullsafety.6'
  flutter:
    sdk: flutter
